import * as fs from 'fs';
import * as path from 'path';

const markdownPath = path.join(process.cwd(), 'src/assets/Money_Masterclass_100_Page_Guide.md');
const rawText = fs.readFileSync(markdownPath, 'utf-8');

// Normalize line endings
const cleanText = rawText.replace(/\r\n/g, '\n');

// Split by Page markers e.g. "Page 1 ", "Page 2 "
const pageRegex = /\n*(Page\s+\d+)\s*\n/g;

interface RawSection {
  pageLabel: string;
  pageNum: number;
  content: string;
}

const sections: RawSection[] = [];
let match: RegExpExecArray | null;
let lastIndex = 0;
let lastPageNum = 0;

// Also catch the first section before Page 1 if any, or process split
const pageSplit = cleanText.split(/(?=\nPage\s+\d+\s*\n)/g);

const parsedPages: any[] = [];

// Helper for Roman numerals
function getRoman(num: number): string {
  const map: [number, string][] = [
    [10, 'X'], [9, 'IX'], [5, 'V'], [4, 'IV'], [1, 'I']
  ];
  let res = '';
  let n = num;
  for (const [val, str] of map) {
    while (n >= val) {
      res += str;
      n -= val;
    }
  }
  return res;
}

const MODULE_TITLES: { [key: number]: string } = {
  1: 'Foundation: What Money Really Is',
  2: 'Flow of Money: How the System Moves',
  3: 'What Schools and Colleges Usually Miss',
  4: 'Analyzing Money: Personal, Business, and Economy',
  5: 'Money Mindset and Behavior',
  6: 'Power of Money',
  7: 'Making Money Work for You',
  8: 'Earning More: Skills, Career, and Business',
  9: 'Protecting Money',
  10: 'Advanced Thinking: Investing, Cycles, and Strategy',
  11: '90-Day Money Operating System'
};

for (const sectionStr of pageSplit) {
  const trimStr = sectionStr.trim();
  if (!trimStr) continue;

  const pageHeaderMatch = trimStr.match(/^Page\s+(\d+)/i);
  let pageNum = 0;
  let bodyStr = trimStr;
  if (pageHeaderMatch) {
    pageNum = parseInt(pageHeaderMatch[1], 10);
    bodyStr = trimStr.replace(/^Page\s+\d+\s*/i, '').trim();
  }

  // Detect module
  const moduleMatch = bodyStr.match(/Module\s+(\d+):\s*([^\n]+)/i);
  let moduleNumber = 0;
  let moduleTitle = '';
  if (moduleMatch) {
    moduleNumber = parseInt(moduleMatch[1], 10);
    moduleTitle = moduleMatch[2].trim();
  }

  // Detect topic title ## **X. Topic Title**
  const titleMatch = bodyStr.match(/##\s*\*\*(\d+)\.\s*([^*]+)\*\*/i) || bodyStr.match(/##\s*\*\*([^*]+)\*\*/i) || bodyStr.match(/##\s*(.+)/);
  let title = '';
  let topicNum: number | undefined = undefined;
  if (titleMatch) {
    if (titleMatch[2]) {
      topicNum = parseInt(titleMatch[1], 10);
      title = titleMatch[2].trim();
    } else {
      title = titleMatch[1].replace(/^\*\*|\*\*$/g, '').trim();
    }
  } else {
    title = `Page ${pageNum}`;
  }

  // Clean footer line
  bodyStr = bodyStr.replace(/Money Masterclass - Educational guide, not financial advice\s*$/i, '').trim();

  parsedPages.push({
    id: `page-${pageNum}`,
    pageNumber: pageNum,
    topicNumber: topicNum,
    moduleNumber,
    moduleTitle: moduleTitle || (moduleNumber ? MODULE_TITLES[moduleNumber] : ''),
    title,
    content: bodyStr
  });
}

// Group into modules
const modulesMap: { [key: number]: any } = {};

for (let i = 1; i <= 11; i++) {
  modulesMap[i] = {
    id: i,
    roman: getRoman(i),
    title: MODULE_TITLES[i],
    pages: []
  };
}

const introPages: any[] = [];
const referencePages: any[] = [];

for (const p of parsedPages) {
  if (p.moduleNumber && modulesMap[p.moduleNumber]) {
    modulesMap[p.moduleNumber].pages.push(p);
  } else if (p.pageNumber <= 4) {
    introPages.push(p);
  } else {
    referencePages.push(p);
  }
}

const modulesList = Object.values(modulesMap);

const tsContent = `// Auto-generated by scripts/build-book-data.ts
export interface PageItem {
  id: string;
  pageNumber: number;
  topicNumber?: number;
  moduleNumber: number;
  moduleTitle: string;
  title: string;
  content: string;
}

export interface ModuleItem {
  id: number;
  roman: string;
  title: string;
  pages: PageItem[];
}

export interface BookData {
  introPages: PageItem[];
  referencePages: PageItem[];
  modules: ModuleItem[];
  allPages: PageItem[];
}

export const BOOK_DATA: BookData = ${JSON.stringify({
  introPages,
  referencePages,
  modules: modulesList,
  allPages: parsedPages
}, null, 2)};
`;

const outputPath = path.join(process.cwd(), 'src/app/data/book-data.ts');
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, tsContent, 'utf-8');

console.log(`Successfully generated book-data.ts with ${parsedPages.length} pages across ${modulesList.length} modules.`);
